# Generated by Django 4.0.5 on 2022-07-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_level', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='supervizor',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='workexperiences',
            options={'ordering': ('pk',)},
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
