# Generated by Django 4.0.5 on 2022-07-03 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0003_rename_sv_image_user_id_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='electronic_signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.office'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
