# Generated by Django 4.0.5 on 2022-07-04 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_company_alter_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(max_length=250, null=True)),
                ('street', models.CharField(max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('tel1', models.CharField(max_length=50)),
                ('tel2', models.CharField(blank=True, max_length=50, null=True)),
                ('tel3', models.CharField(blank=True, max_length=50, null=True)),
                ('tel4', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('gender', models.CharField(blank=True, choices=[('Kişi', 'Kişi'), ('Qadın', 'Qadın')], default=None, max_length=150, null=True)),
                ('customer_type', models.CharField(choices=[('ŞƏXS', 'ŞƏXS'), ('KORPORATİV', 'KORPORATİV')], default=None, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-pk',)},
        ),
        migrations.CreateModel(
            name='WorkExperiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('start_job_date', models.DateField(blank=True, default=None, null=True)),
                ('end_job_date', models.DateField(blank=True, default=None, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supervizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervizor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervizor', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='supervizor_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('knowledge_level', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('knowledge_level', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='account.address')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='account.customer')),
            ],
        ),
    ]
