# Generated by Django 4.0.5 on 2022-07-04 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_district_alter_address_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlanguage',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='user',
            name='driving_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Xidməti müqavilə', 'Xidməti müqavilə'), ('Əmək müqaviləsi', 'Əmək müqaviləsi'), ('Təcrübəçi', 'Təcrübəçi')], default='Əmək müqaviləsi', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='family_composition',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='martial_status',
            field=models.CharField(blank=True, choices=[('Evli', 'Evli'), ('Subay', 'Subay')], default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/account/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='speaking_language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='work_phone2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='listening',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='reading',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userlanguage',
            name='speeking',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='knowledge_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_school', models.CharField(blank=True, max_length=500, null=True)),
                ('college', models.CharField(blank=True, max_length=500, null=True)),
                ('university', models.CharField(blank=True, max_length=500, null=True)),
                ('diploma', models.ImageField(blank=True, null=True, upload_to='media/account/education/%Y/%m/%d/', validators=[main.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
