# Generated by Django 4.0.5 on 2022-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userlanguage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
