version: "3.3"

services:
  web:
    build: .
    restart: unless-stopped
    image: kodaze-web
    networks:
      - kodaze-network
    # '/start' is the shell script used to run the service
    #command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/code
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - STATIC_ROOT=/app/static
      - MEDIA_URL=/app/media/
    links:
      - db

  db:
    image: library/postgres:14.2-alpine
    restart: unless-stopped
    networks:
      - kodaze-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
volumes:
  postgres_data:
    driver: local
  media:  
    driver: local

networks:
  kodaze-network:
    driver: bridge